REM ******************************************************************
REM Fecha         : 26/03/2018
REM Realizado por : TheOverLordKotan
REM Base de Datos : FS_ADDEP_US
REM ******************************************************************

REM TABLESPACE Y SEGMENTOS DE ROLLBACK
set feedback off
spool TMP.lst
select distinct 'pause DEBE estar conectado con Usuario SYSTEM' || chr(10) || 'ROLL' || chr(10) || 'EXIT'
from dual
where user <> 'SYSTEM'
/
spool off
start TMP.lst
set feedback on






	DROP TABLE   "FS_ADDEP_US"."EQ_CVCT" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."EQ_EQPO" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."TN_TREQ" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."TN_TRNE" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."US_CVJU" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."US_DTEQ" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."US_JDEQ" CASCADE CONSTRAINTS;


	DROP TABLE   "FS_ADDEP_US"."US_PSNA" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."US_ROLS" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."US_SRVI" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_ADDEP_US"."US_SVRS" CASCADE CONSTRAINTS;

    DROP TABLE   "FS_ADDEP_US"."US_USRI" CASCADE CONSTRAINTS;
    
    DROP TABLE   "FS_ADDEP_US"."US_USRS" CASCADE CONSTRAINTS;

    
    DROP SEQUENCE "FS_ADDEP_US"."ID_PERONSA";
    DROP SEQUENCE "FS_ADDEP_US"."ID_USUARIO";
    DROP SEQUENCE "FS_ADDEP_US"."ID_EQUIPO";
    DROP SEQUENCE "FS_ADDEP_US"."ID_DT_EQUIPO";
    DROP SEQUENCE "FS_ADDEP_US"."ID_CONVOCATORIA";


          
          
          
    
    REM USUARIO  DUENHO DEL APLICATIVO FS_ADDEP_US
drop user FS_ADDEP_US cascade;

REM TABLESPACE DE DATOS
DROP TABLESPACE TS_TADDEP   INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
/

REM TABLESPACE DE INDICES 
DROP TABLESPACE TS_ADDEP INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
/

REM TABLESPACE TEMPORAL
DROP tablespace TS_IADDEP INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
/






