--Secuencia de autoincrementar para la tabla Persona
CREATE SEQUENCE FS_ADDEP_US.ID_PERONSA  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE FS_ADDEP_US.ID_USUARIO  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE FS_ADDEP_US.ID_EQUIPO  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE FS_ADDEP_US.ID_DT_EQUIPO  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE FS_ADDEP_US.ID_CONVOCATORIA  START WITH 1 INCREMENT BY 1;


