--Secuencia de autoincrementar para la tabla Persona
CREATE SEQUENCE ID_PERONSA  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_USUARIO  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_EQUIPO  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_DT_EQUIPO  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_CONVOCATORIA  START WITH 1 INCREMENT BY 1;


