/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:11:25 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */




CREATE INDEX "IXFK_EQ_CVCT_EQ_EQPO"   
 ON  "FS_ADDEP_US"."FS_ADDEP_US"."EQ_CVCT" ("CVCT_EQPO") 
;

