/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:13:46 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */



CREATE TABLE  "TN_TRNE"
(
	"TRNE_TRNE" NUMBER(32) NOT NULL, --"id torneo"
	"TRNE_TRNB" VARCHAR2(250) NULL,	 --"nombre del torneo"
	"TRNE_NMEQ" NUMBER(32) NULL,	 --"numero de equipos"
	"TRNE_ESDO" NUMBER(8,2) NULL	 --"estado"
)
;

COMMENT ON TABLE TN_TRNE 					IS 'Contiene los torneos registrados'
;
COMMENT ON COLUMN TN_TRNE.TRNE_TRNE			IS 'Identificador unico por torneo'
;
COMMENT ON COLUMN TN_TRNE.TRNE_TRNB  		IS 'Numero de equipos que pueden pertenecer a un torneo'
;
COMMENT ON COLUMN TN_TRNE.TRNE_NMEQ  		IS 'Estado de los equipos'
;
COMMENT ON COLUMN TN_TRNE.TRNE_ESDO  		IS 'Estado del torneo'
;

ALTER TABLE  "TN_TRNE" 
 ADD CONSTRAINT "PK_TN_TRNE"
	PRIMARY KEY ("TRNE_TRNE") 
 USING INDEX
;
