/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:13:06 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */





CREATE INDEX "IXFK_TN_TREQ_TN_TRNE"   
 ON  "TN_TREQ" ("TREQ_TRNE") 
;


