/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:15:49 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */



CREATE INDEX "IXFK_US_JDEQ_EQ_EQPO"   
 ON  "US_JDEQ" ("JDEQ_EQPO") 
;

CREATE INDEX "IXFK_US_JDEQ_US_USRI"   
 ON  "US_JDEQ" ("JDEQ_USRI") 
;

