/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:18:00 p.m. 			*/
/*  DBMS       : Oracle 								-*/
/* ---------------------------------------------------- */





CREATE INDEX "IXFK_US_USRS_US_ROLS"   
 ON  "US_USRS" ("USRS_ROLS") 
;

CREATE INDEX "IXFK_US_USRS_US_USRI"   
 ON  "US_USRS" ("USRS_USRI") 
;

