/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:17:38 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */




CREATE INDEX "IXFK_US_USRI_US_PSNA"   
 ON  "FS_ADDEP_US"."US_USRI" ("USRI_PSNA") 
;


