/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:11 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */




CREATE INDEX "IXFK_US_CVJU_EQ_CVCT"   
 ON  "US_CVJU" ("CVJU_CVCT") 
;

CREATE INDEX "IXFK_US_CVJU_US_USRI"   
 ON  "US_CVJU" ("CVJU_USRI") 
;


