/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:29 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */




CREATE INDEX "IXFK_US_DTEQ_EQ_EQPO"   
 ON  "FS_ADDEP_US"."US_DTEQ" ("DTEQ_EQPO") 
;

CREATE INDEX "IXFK_US_DTEQ_US_USRI"   
 ON  "FS_ADDEP_US"."US_DTEQ" ("DTEQ_USRI") 
;

