/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:17:02 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */



CREATE INDEX "IXFK_US_SVRS_US_ROLS"   
 ON  "US_SVRS" ("SVRS_ROLS") 
;

CREATE INDEX "IXFK_US_SVRS_US_SRVI"   
 ON  "US_SVRS" ("SVRS_SRVI") 
;

