/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:11:25 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */




ALTER TABLE  "EQ_CVCT" 
 ADD CONSTRAINT "FK_EQ_CVCT_EQ_EQPO"
	FOREIGN KEY ("CVCT_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;
