/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:13:06 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */



ALTER TABLE  "TN_TREQ" 
 ADD CONSTRAINT "FK_TN_TREQ_EQ_EQPO"
	FOREIGN KEY ("TREQ_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;

ALTER TABLE  "TN_TREQ" 
 ADD CONSTRAINT "FK_TN_TREQ_TN_TRNE"
	FOREIGN KEY ("TREQ_TRNE") REFERENCES  "TN_TRNE" ("TRNE_TRNE")
;
