

ALTER TABLE  "US_SVRS" 
 ADD CONSTRAINT "FK_US_SVRS_US_ROLS"
	FOREIGN KEY ("SVRS_ROLS") REFERENCES  "US_ROLS" ("ROLS_ROLS")
;

ALTER TABLE  "US_SVRS" 
 ADD CONSTRAINT "FK_US_SVRS_US_SRVI"
	FOREIGN KEY ("SVRS_SRVI") REFERENCES  "US_SRVI" ("SRVI_SRVI")
;
