/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:15:49 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */




ALTER TABLE  "US_JDEQ" 
 ADD CONSTRAINT "FK_US_JDEQ_EQ_EQPO"
	FOREIGN KEY ("JDEQ_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;

ALTER TABLE  "US_JDEQ" 
 ADD CONSTRAINT "FK_US_JDEQ_US_USRI"
	FOREIGN KEY ("JDEQ_USRI") REFERENCES  "US_USRI" ("USRI_USRI")
;
