/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:29 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */




ALTER TABLE  "FS_ADDEP_US"."US_DTEQ" 
 ADD CONSTRAINT "FK_US_DTEQ_EQ_EQPO"
	FOREIGN KEY ("DTEQ_EQPO") REFERENCES  "FS_ADDEP_US"."EQ_EQPO" ("EQPO_EQPO")
;

ALTER TABLE  "FS_ADDEP_US"."US_DTEQ" 
 ADD CONSTRAINT "FK_US_DTEQ_US_USRI"
	FOREIGN KEY ("DTEQ_USRI") REFERENCES  "FS_ADDEP_US"."US_USRI" ("USRI_USRI")
;
