/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:18:00 p.m. 			*/
/*  DBMS       : Oracle 								-*/
/* ---------------------------------------------------- */




ALTER TABLE  "US_USRS" 
 ADD CONSTRAINT "FK_US_USRS_US_ROLS"
	FOREIGN KEY ("USRS_ROLS") REFERENCES  "US_ROLS" ("ROLS_ROLS")
;

ALTER TABLE  "US_USRS" 
 ADD CONSTRAINT "FK_US_USRS_US_USRI"
	FOREIGN KEY ("USRS_USRI") REFERENCES  "US_USRI" ("USRI_USRI")
;
