

ALTER TABLE  "FS_ADDEP_US"."US_SVRS" 
 ADD CONSTRAINT "FK_US_SVRS_US_ROLS"
	FOREIGN KEY ("SVRS_ROLS") REFERENCES  "FS_ADDEP_US"."US_ROLS" ("ROLS_ROLS")
;

ALTER TABLE  "FS_ADDEP_US"."US_SVRS" 
 ADD CONSTRAINT "FK_US_SVRS_US_SRVI"
	FOREIGN KEY ("SVRS_SRVI") REFERENCES  "FS_ADDEP_US"."US_SRVI" ("SRVI_SRVI")
;
