/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:11:25 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */



CREATE TABLE  "EQ_CVCT"
(
	"CVCT_CVCT" 	NUMBER(32) NOT NULL,	--"id convocatoria"
	"CVCT_EQPO" 	NUMBER(32) NOT NULL,	--"id equipo"
	"CVCT_ESDO" 	NUMBER(8) NOT NULL		--"estado"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE EQ_CVCT 					IS 'Contiene las convocatoria por cada equipo'
;
COMMENT ON COLUMN EQ_CVCT.CVCT_CVCT		    IS 'Identificador unico de la convocataoria'
;
COMMENT ON COLUMN EQ_CVCT.CVCT_EQPO  		IS 'identificador del equipo'
;
COMMENT ON COLUMN EQ_CVCT.CVCT_ESDO  		IS 'Estado de la convocatoria'
;

ALTER TABLE  "EQ_CVCT" 
 ADD CONSTRAINT "PK_EQ_CVCT"
	PRIMARY KEY ("CVCT_CVCT") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );

CREATE INDEX "IXFK_EQ_CVCT_EQ_EQPO"   
 ON  "EQ_CVCT" ("CVCT_EQPO") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "EQ_CVCT" 
 ADD CONSTRAINT "FK_EQ_CVCT_EQ_EQPO"
	FOREIGN KEY ("CVCT_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;
