/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:12:30 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */


CREATE TABLE  "EQ_EQPO"
(
	"EQPO_EQPO" NUMBER(32) NOT NULL, --"id equipo"
	"EQPO_NBEQ" VARCHAR2(250) NULL,	 --"Nombre de equipo"
	"EQPO_ESDO" NUMBER(8) NULL		 --"Estado del equipo"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE EQ_EQPO 					IS 'Contiene llos equipos registrados'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_EQPO		IS 'Identificador unico por equipo'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_NBEQ  		IS 'Contiene los nombres de los equipos registrados'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_ESDO  		IS 'Estado de los equipos'
;

ALTER TABLE  "EQ_EQPO" 
 ADD CONSTRAINT "PK_EQ_EQPO"
	PRIMARY KEY ("EQPO_EQPO") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );