/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:12:30 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */


CREATE TABLE  "EQ_EQPO"
(
	"EQPO_EQPO" NUMBER(32) NOT NULL, --"id equipo"
	"EQPO_NBEQ" VARCHAR2(250) NULL,	 --"Nombre de equipo"
	"EQPO_ESDO" NUMBER(8) NULL		 --"Estado del equipo"
)
;

COMMENT ON TABLE EQ_EQPO 					IS 'Contiene llos equipos registrados'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_EQPO		IS 'Identificador unico por equipo'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_NBEQ  		IS 'Contiene los nombres de los equipos registrados'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_ESDO  		IS 'Estado de los equipos'
;

ALTER TABLE  "EQ_EQPO" 
 ADD CONSTRAINT "PK_EQ_EQPO"
	PRIMARY KEY ("EQPO_EQPO") 
 USING INDEX
;
