/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:13:06 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */


CREATE TABLE  "TN_TREQ"
(
	"TREQ_TREQ" NUMBER(32) NOT NULL, --"id torneo equipo"
	"TREQ_EQPO" NUMBER(32) NOT NULL, --"id equipo"
	"TREQ_TRNE" NUMBER(32) NULL		 --"id torneo"
)
;

COMMENT ON TABLE EQ_EQPO 					IS 'Contiene llos equipos registrados'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_EQPO		IS 'Identificador unico por equipo'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_NBEQ  		IS 'Contiene los nombres de los equipos registrados'
;
COMMENT ON COLUMN EQ_EQPO.EQPO_ESDO  		IS 'Estado de los equipos'
;

ALTER TABLE  "TN_TREQ" 
 ADD CONSTRAINT "PK_TN_TREQ"
	PRIMARY KEY ("TREQ_TREQ") 
 USING INDEX
;

CREATE INDEX "IXFK_TN_TREQ_EQ_EQPO"   
 ON  "TN_TREQ" ("TREQ_EQPO") 
;

CREATE INDEX "IXFK_TN_TREQ_TN_TRNE"   
 ON  "TN_TREQ" ("TREQ_TRNE") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "TN_TREQ" 
 ADD CONSTRAINT "FK_TN_TREQ_EQ_EQPO"
	FOREIGN KEY ("TREQ_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;

ALTER TABLE  "TN_TREQ" 
 ADD CONSTRAINT "FK_TN_TREQ_TN_TRNE"
	FOREIGN KEY ("TREQ_TRNE") REFERENCES  "TN_TRNE" ("TRNE_TRNE")
;
