/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:13:46 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */



CREATE TABLE  "FS_ADDEP_US"."TN_TRNE"
(
	"TRNE_TRNE" NUMBER(32) NOT NULL, --"id torneo"
	"TRNE_TRNB" VARCHAR2(250) NULL,	 --"nombre del torneo"
	"TRNE_NMEQ" NUMBER(32) NULL,	 --"numero de equipos"
	"TRNE_ESDO" NUMBER(8,2) NULL	 --"estado"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE "FS_ADDEP_US"."TN_TRNE" 					IS 'Contiene los torneos registrados'
;
COMMENT ON COLUMN "FS_ADDEP_US"."TN_TRNE"."TRNE_TRNE"			IS 'Identificador unico por torneo'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."TN_TRNE"."TRNE_TRNB"  		IS 'Numero de equipos que pueden pertenecer a un torneo'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."TN_TRNE"."TRNE_NMEQ"  		IS 'Estado de los equipos'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."TN_TRNE"."TRNE_ESDO"  		IS 'Estado del torneo'
;

ALTER TABLE  "FS_ADDEP_US"."TN_TRNE" 
 ADD CONSTRAINT "PK_TN_TRNE"
	PRIMARY KEY ("TRNE_TRNE") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );
