/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:17:02 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */

CREATE TABLE  "US_SVRS"
(
	"SVRS_ROLS" NUMBER(32) NULL, --"id rol"
	"SVRS_SRVI" NUMBER(32) NULL	 --"id servicio"
)
;

COMMENT ON TABLE US_SVRS IS 'Contiene los roles que pueden acceder a cada servicio'
;
COMMENT ON COLUMN US_SVRS.SVRS_ROLS		  IS 'Contiene el identificador de cada rol'
;
COMMENT ON COLUMN US_SVRS.SVRS_ROLS  IS 'Contiene el identificador de cada servicio'
;

CREATE INDEX "IXFK_US_SVRS_US_ROLS"   
 ON  "US_SVRS" ("SVRS_ROLS") 
;

CREATE INDEX "IXFK_US_SVRS_US_SRVI"   
 ON  "US_SVRS" ("SVRS_SRVI") 
;

ALTER TABLE  "US_SVRS" 
 ADD CONSTRAINT "FK_US_SVRS_US_ROLS"
	FOREIGN KEY ("SVRS_ROLS") REFERENCES  "US_ROLS" ("ROLS_ROLS")
;

ALTER TABLE  "US_SVRS" 
 ADD CONSTRAINT "FK_US_SVRS_US_SRVI"
	FOREIGN KEY ("SVRS_SRVI") REFERENCES  "US_SRVI" ("SRVI_SRVI")
;
