/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:16:04 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */


CREATE TABLE  "FS_ADDEP_US"."US_PSNA"
(
	"PSNA_PSNA" 	NUMBER(32) NOT NULL,		--"Id de la persona"
	"PSNA_NOBR" 	VARCHAR2(250) NOT NULL,		--"Nombre persona"
	"PSNA_APDO" 	VARCHAR2(250) NOT NULL,		--"Apellido persona"
	"PSNA_TPDOC"	VARCHAR2(250) NOT NULL,		--"Tipo de documento"
	"PSNA_DOTO" 	NUMBER(32) NOT NULL,		--"Numero de documento"
	"PSNA_FCNA" 	DATE NOT NULL				--"Fecha de nacimiento de la persona"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE "FS_ADDEP_US"."US_PSNA" 				IS 'Contiene los datos de las personas registradas'
;
COMMENT ON COLUMN "FS_ADDEP_US"."US_PSNA"."PSNA_PSNA"  	IS 'Identificador unico de la persona'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_PSNA"."PSNA_NOBR"  	IS 'Contiene el nombre de la persona'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_PSNA"."PSNA_APDO"  	IS 'Contiene el apellido de la persona'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_PSNA"."PSNA_TPDOC"   	IS 'Contiene el tipo de documento'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_PSNA"."PSNA_DOTO"  	IS 'Contiene el numero de documento '
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_PSNA"."PSNA_TPDOC"   	IS 'Contiene la fecha de nacimiento de la persona'
;


ALTER TABLE  "FS_ADDEP_US"."US_PSNA" 
 ADD CONSTRAINT "PK_US_PSNA"
	PRIMARY KEY ("PSNA_PSNA") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );
