/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:11 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */



CREATE TABLE  "US_CVJU"
(
	"CVJU_CVJU" NUMBER(32) NOT NULL, --"id convocatori jugador"
	"CVJU_CVCT" NUMBER(32) NOT NULL, --"id convocatoria"
	"CVJU_ESDO" NUMBER(8) NULL,		 --"estado"
	"CVJU_USRI" NUMBER(32) NOT NULL  --"id usuario"
)
;

COMMENT ON TABLE US_CVJU 					IS 'Contiene datos de los jugadores preinscritos a un equipo'
;
COMMENT ON COLUMN US_CVJU.CVJU_CVJU			IS 'Identificador unico de convocatoria jugador'
;
COMMENT ON COLUMN US_CVJU.CVJU_CVCT  		IS 'Identificador de la convocatoria'
;
COMMENT ON COLUMN US_CVJU.CVJU_ESDO  		IS 'Estado de la convocatoria jugador'
;
COMMENT ON COLUMN US_CVJU.CVJU_USRI  		IS 'id del usuario'
;

ALTER TABLE  "US_CVJU" 
 ADD CONSTRAINT "PK_US_CVJU"
	PRIMARY KEY ("CVJU_CVJU") 
 USING INDEX
;

CREATE INDEX "IXFK_US_CVJU_EQ_CVCT"   
 ON  "US_CVJU" ("CVJU_CVCT") 
;

CREATE INDEX "IXFK_US_CVJU_US_USRI"   
 ON  "US_CVJU" ("CVJU_USRI") 
;


ALTER TABLE  "US_CVJU" 
 ADD CONSTRAINT "FK_US_CVJU_EQ_CVCT"
	FOREIGN KEY ("CVJU_CVCT") REFERENCES  "EQ_CVCT" ("CVCT_CVCT")
;

ALTER TABLE  "US_CVJU" 
 ADD CONSTRAINT "FK_US_CVJU_US_USRI"
	FOREIGN KEY ("CVJU_USRI") REFERENCES  "US_USRI" ("USRI_USRI")
;
