/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:16:21 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */



CREATE TABLE  "US_ROLS"
(
	"ROLS_ROLS" 		NUMBER(32) NOT NULL,		--"id rol"
	"ROLS_NORS" 		VARCHAR(250) NOT NULL,		--"nombre rol"
	"ROLS_ESDO" 		NUMBER(32) NOT NULL		--"Estado rol"
)
;

COMMENT ON TABLE US_ROLS IS 'Contiene los roles'
;
COMMENT ON COLUMN US_ROLS.ROLS_ROLS		  IS 'Identificador unico del rol'
;
COMMENT ON COLUMN US_ROLS.ROLS_NORS  IS 'Nombre del rol'
;
COMMENT ON COLUMN US_ROLS.ROLS_ESDO  IS 'estado rol'
;

ALTER TABLE  "US_ROLS" 
 ADD CONSTRAINT "PK_US_ROLS"
	PRIMARY KEY ("ROLS_ROLS") 
 USING INDEX
;
