/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:17:38 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */



CREATE TABLE  "US_USRI"
(
	"USRI_USRI" 		NUMBER(32) NOT NULL,		--"Id de usuario"
	"USRI_NUSR" 		VARCHAR2(250) NOT NULL,		--"Nombre de usuario"
	"USRI_CTUS" 		VARCHAR2(250) NOT NULL,		--"Contrasena de usuario"
	"USRI_ESDO" 		NUMBER(8) NULL,				--"Estado de usuario"
	"USRI_PSNA" 		NUMBER(32) NOT NULL			--"Id de persona"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE US_USRI 				IS 'Contiene los datos los usuarios registrados'
;
COMMENT ON COLUMN US_USRI.USRI_USRI  	IS 'Identificador unico del usuario'
;
COMMENT ON COLUMN US_USRI.USRI_NUSR  	IS 'Contiene el nombre registrado por el usuario'
;
COMMENT ON COLUMN US_USRI.USRI_CTUS  	IS 'Contiene la contraseña registrada por el usuario'
;
COMMENT ON COLUMN US_USRI.USRI_ESDO   	IS 'Contiene el estado en el que se encuentra el usuario'
;
COMMENT ON COLUMN US_USRI.USRI_PSNA   	IS 'Contiene el identificador unico del usuario'
;

ALTER TABLE  "US_USRI" 
 ADD CONSTRAINT "PK_US_USRI"
	PRIMARY KEY ("USRI_USRI") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );

