/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:18:00 p.m. 			*/
/*  DBMS       : Oracle 								-*/
/* ---------------------------------------------------- */



CREATE TABLE  "FS_ADDEP_US"."US_USRS"
(
	"USRS_ROLS" 		NUMBER(32) NULL,  --"Id roles"
	"USRS_USRI" 		NUMBER(32) NULL	  --"Id usuario"	
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE "FS_ADDEP_US"."US_USRS" 				IS 'Contiene los roles que tiene cada usuario'
;
COMMENT ON COLUMN "FS_ADDEP_US"."US_USRS"."USRS_ROLS"  	IS 'Identificador unico del rol'
;
COMMENT ON COLUMN "FS_ADDEP_US"."US_USRS"."USRS_USRI"  	IS 'Identificador unico del usuario'
;

