/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:16:43 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */



CREATE TABLE  "US_SRVI"
(
	"SRVI_SRVI" 	NUMBER(32) NOT NULL,	--"Id de servicio"
	"SRVI_NBSV" 	VARCHAR2(50) NULL		--"Nombre de servicio"
)
;

COMMENT ON TABLE US_SRVI IS 'Contiene los servicios'
;
COMMENT ON COLUMN US_SRVI.SRVI_SRVI		  IS 'Identificador unico del servicio'
;
COMMENT ON COLUMN US_SRVI.SRVI_NBSV  IS 'Nombre del servico'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "US_SRVI" 
 ADD CONSTRAINT "PK_US_SRVI"
	PRIMARY KEY ("SRVI_SRVI") 
 USING INDEX
;
