/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:18:00 p.m. 			*/
/*  DBMS       : Oracle 								-*/
/* ---------------------------------------------------- */



CREATE TABLE  "US_USRS"
(
	"USRS_ROLS" 		NUMBER(32) NULL,  --"Id roles"
	"USRS_USRI" 		NUMBER(32) NULL	  --"Id usuario"	
)
;

COMMENT ON TABLE US_USRS 				IS 'Contiene los roles que tiene cada usuario'
;
COMMENT ON COLUMN US_USRS.USRS_ROLS  	IS 'Identificador unico del rol'
;
COMMENT ON COLUMN US_USRS.USRS_USRI  	IS 'Identificador unico del usuario'
;

CREATE INDEX "IXFK_US_USRS_US_ROLS"   
 ON  "US_USRS" ("USRS_ROLS") 
;

CREATE INDEX "IXFK_US_USRS_US_USRI"   
 ON  "US_USRS" ("USRS_USRI") 
;



ALTER TABLE  "US_USRS" 
 ADD CONSTRAINT "FK_US_USRS_US_ROLS"
	FOREIGN KEY ("USRS_ROLS") REFERENCES  "US_ROLS" ("ROLS_ROLS")
;

ALTER TABLE  "US_USRS" 
 ADD CONSTRAINT "FK_US_USRS_US_USRI"
	FOREIGN KEY ("USRS_USRI") REFERENCES  "US_USRI" ("USRI_USRI")
;
