/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:15:49 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */


CREATE TABLE  "US_JDEQ"
(
	"JDEQ_JDEQ" 	NUMBER(32) NOT NULL,	 --"id jugador equipo"
	"JDEQ_EQPO" 	NUMBER(32) NOT NULL,	 --"nombre equipo"
	"JDEQ_ESDO" 	NUMBER(8) NULL,			 --"estado equipo"
	"JDEQ_USRI" 	NUMBER(32) NOT NULL		 --"id usuario"
)
;

COMMENT ON TABLE US_JDEQ IS 'Contiene los jugadores con su respectivo equipo'
;
COMMENT ON COLUMN US_JDEQ.JDEQ_JDEQ		  IS 'Identificador unico de jugadorequipo'
;
COMMENT ON COLUMN US_JDEQ.JDEQ_EQPO  IS 'Nombre de equipo'
;
COMMENT ON COLUMN US_JDEQ.JDEQ_ESDO  IS 'estado del equipo'
;
COMMENT ON COLUMN US_JDEQ.JDEQ_USRI  IS 'identificador del usuario'
;

ALTER TABLE  "US_JDEQ" 
 ADD CONSTRAINT "PK_US_JDEQ"
	PRIMARY KEY ("JDEQ_JDEQ") 
 USING INDEX
;

CREATE INDEX "IXFK_US_JDEQ_EQ_EQPO"   
 ON  "US_JDEQ" ("JDEQ_EQPO") 
;

CREATE INDEX "IXFK_US_JDEQ_US_USRI"   
 ON  "US_JDEQ" ("JDEQ_USRI") 
;

ALTER TABLE  "US_JDEQ" 
 ADD CONSTRAINT "FK_US_JDEQ_EQ_EQPO"
	FOREIGN KEY ("JDEQ_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;

ALTER TABLE  "US_JDEQ" 
 ADD CONSTRAINT "FK_US_JDEQ_US_USRI"
	FOREIGN KEY ("JDEQ_USRI") REFERENCES  "US_USRI" ("USRI_USRI")
;
