/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:11 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */



CREATE TABLE  "FS_ADDEP_US"."US_CVJU"
(
	"CVJU_CVJU" NUMBER(32) NOT NULL, --"id convocatori jugador"
	"CVJU_CVCT" NUMBER(32) NOT NULL, --"id convocatoria"
	"CVJU_ESDO" NUMBER(8) NULL,		 --"estado"
	"CVJU_USRI" NUMBER(32) NOT NULL  --"id usuario"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE "FS_ADDEP_US"."US_CVJU" 					IS 'Contiene datos de los jugadores preinscritos a un equipo'
;
COMMENT ON COLUMN "FS_ADDEP_US"."US_CVJU"."CVJU_CVJU"			IS 'Identificador unico de convocatoria jugador'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_CVJU"."CVJU_CVCT"  		IS 'Identificador de la convocatoria'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_CVJU"."CVJU_ESDO"  		IS 'Estado de la convocatoria jugador'
;                                         
COMMENT ON COLUMN "FS_ADDEP_US"."US_CVJU"."CVJU_USRI"  		IS 'id del usuario'
;

ALTER TABLE  "FS_ADDEP_US"."US_CVJU" 
 ADD CONSTRAINT "PK_US_CVJU"
	PRIMARY KEY ("CVJU_CVJU") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );