/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:29 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */


CREATE TABLE  "US_DTEQ"
(
	"DTEQ_DTEQ" NUMBER(32) NOT NULL, --"id directivas equipo"
	"DTEQ_EQPO" NUMBER(32) NOT NULL, --"id equipo"
	"DTEQ_ESDO" NUMBER(8) NOT NULL,  --"estado"
	"DTEQ_USRI" NUMBER(32) NOT NULL  --"id usuario"
)
;

COMMENT ON TABLE US_DTEQ 					IS 'Contiene datos de los directivos de un equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_DTEQ			IS 'Identificador unico de los directivos del equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_EQPO  		IS 'Identificador de equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_ESDO  		IS 'Estado de los directivos del equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_USRI  		IS 'id del usuario'
;

ALTER TABLE  "US_DTEQ" 
 ADD CONSTRAINT "PK_US_DTEQ"
	PRIMARY KEY ("DTEQ_DTEQ") 
 USING INDEX
;

CREATE INDEX "IXFK_US_DTEQ_EQ_EQPO"   
 ON  "US_DTEQ" ("DTEQ_EQPO") 
;

CREATE INDEX "IXFK_US_DTEQ_US_USRI"   
 ON  "US_DTEQ" ("DTEQ_USRI") 
;

ALTER TABLE  "US_DTEQ" 
 ADD CONSTRAINT "FK_US_DTEQ_EQ_EQPO"
	FOREIGN KEY ("DTEQ_EQPO") REFERENCES  "EQ_EQPO" ("EQPO_EQPO")
;

ALTER TABLE  "US_DTEQ" 
 ADD CONSTRAINT "FK_US_DTEQ_US_USRI"
	FOREIGN KEY ("DTEQ_USRI") REFERENCES  "US_USRI" ("USRI_USRI")
;
