/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:14:29 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */


CREATE TABLE  "US_DTEQ"
(
	"DTEQ_DTEQ" NUMBER(32) NOT NULL, --"id directivas equipo"
	"DTEQ_EQPO" NUMBER(32) NOT NULL, --"id equipo"
	"DTEQ_ESDO" NUMBER(8) NOT NULL,  --"estado"
	"DTEQ_USRI" NUMBER(32) NOT NULL  --"id usuario"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE US_DTEQ 					IS 'Contiene datos de los directivos de un equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_DTEQ			IS 'Identificador unico de los directivos del equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_EQPO  		IS 'Identificador de equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_ESDO  		IS 'Estado de los directivos del equipo'
;
COMMENT ON COLUMN US_DTEQ.DTEQ_USRI  		IS 'id del usuario'
;

ALTER TABLE  "US_DTEQ" 
 ADD CONSTRAINT "PK_US_DTEQ"
	PRIMARY KEY ("DTEQ_DTEQ") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IADDEP 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE 
 ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
 );