/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-abr.-2018 12:17:02 p.m. 			*/
/*  DBMS       : Oracle 								*/
/* ---------------------------------------------------- */

CREATE TABLE  "US_SVRS"
(
	"SVRS_ROLS" NUMBER(32) NULL, --"id rol"
	"SVRS_SRVI" NUMBER(32) NULL	 --"id servicio"
)
TABLESPACE	TS_ADDEP
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE US_SVRS IS 'Contiene los roles que pueden acceder a cada servicio'
;
COMMENT ON COLUMN US_SVRS.SVRS_ROLS		  IS 'Contiene el identificador de cada rol'
;
COMMENT ON COLUMN US_SVRS.SVRS_ROLS  IS 'Contiene el identificador de cada servicio'
;

