
SET DEFINE OFF;
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('1','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('5','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('3','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('4','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('6','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('21','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('22','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('25','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('26','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('27','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('28','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('35','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('36','1','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('40','313','0');
Insert into OW_JST_US.EQ_CVCT (CVCT_CVCT,CVCT_EQPO,CVCT_ESDO) values ('41','313','0');
REM INSERTING into OW_JST_US.EQ_EQPO
SET DEFINE OFF;
Insert into OW_JST_US.EQ_EQPO (EQPO_EQPO,EQPO_NBEQ,EQPO_ESDO) values ('4','b','0');
Insert into OW_JST_US.EQ_EQPO (EQPO_EQPO,EQPO_NBEQ,EQPO_ESDO) values ('312','eeee','0');
Insert into OW_JST_US.EQ_EQPO (EQPO_EQPO,EQPO_NBEQ,EQPO_ESDO) values ('35','Colombia FC','0');
Insert into OW_JST_US.EQ_EQPO (EQPO_EQPO,EQPO_NBEQ,EQPO_ESDO) values ('313','qqq','0');
Insert into OW_JST_US.EQ_EQPO (EQPO_EQPO,EQPO_NBEQ,EQPO_ESDO) values ('316','xxx','0');
Insert into OW_JST_US.EQ_EQPO (EQPO_EQPO,EQPO_NBEQ,EQPO_ESDO) values ('1','Colombia F.C','0');
REM INSERTING into OW_JST_US.PRUEBA_TIPO_DOCUMENTO
SET DEFINE OFF;
Insert into OW_JST_US.PRUEBA_TIPO_DOCUMENTO (ID,TIPO_DOCUMENTO) values ('1','CEDULA');
Insert into OW_JST_US.PRUEBA_TIPO_DOCUMENTO (ID,TIPO_DOCUMENTO) values ('2','TARJETA IDENTIDAD');
Insert into OW_JST_US.PRUEBA_TIPO_DOCUMENTO (ID,TIPO_DOCUMENTO) values ('3','PASAPORTE');
REM INSERTING into OW_JST_US.TN_TREQ
SET DEFINE OFF;
REM INSERTING into OW_JST_US.TN_TRNE
SET DEFINE OFF;
Insert into OW_JST_US.TN_TRNE (TRNE_TRNE,TRNE_TRNB,TRNE_NMEQ,TRNE_ESDO) values ('2','Torneo Colombia','32','0');
Insert into OW_JST_US.TN_TRNE (TRNE_TRNE,TRNE_TRNB,TRNE_NMEQ,TRNE_ESDO) values ('1','Torneo Bogota','10','0');
REM INSERTING into OW_JST_US.US_CVJU
SET DEFINE OFF;
REM INSERTING into OW_JST_US.US_DTEQ
SET DEFINE OFF;
Insert into OW_JST_US.US_DTEQ (DTEQ_DTEQ,DTEQ_EQPO,DTEQ_ESDO,DTEQ_USRI) values ('313','313','0','24');
Insert into OW_JST_US.US_DTEQ (DTEQ_DTEQ,DTEQ_EQPO,DTEQ_ESDO,DTEQ_USRI) values ('1','1','0','44');
Insert into OW_JST_US.US_DTEQ (DTEQ_DTEQ,DTEQ_EQPO,DTEQ_ESDO,DTEQ_USRI) values ('4','4','0','38');
Insert into OW_JST_US.US_DTEQ (DTEQ_DTEQ,DTEQ_EQPO,DTEQ_ESDO,DTEQ_USRI) values ('35','35','0','1');
Insert into OW_JST_US.US_DTEQ (DTEQ_DTEQ,DTEQ_EQPO,DTEQ_ESDO,DTEQ_USRI) values ('312','312','0','23');
Insert into OW_JST_US.US_DTEQ (DTEQ_DTEQ,DTEQ_EQPO,DTEQ_ESDO,DTEQ_USRI) values ('316','316','0','25');
REM INSERTING into OW_JST_US.US_JDEQ
SET DEFINE OFF;
REM INSERTING into OW_JST_US.US_PSNA
SET DEFINE OFF;
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('38','A','B','CC','12374',to_date('11/02/92','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('41','Joan','Torres','Pasaporte','1024518884',to_date('03/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('40','q','q','Cedula','1209',null);
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('42','q','q','TarjetaIdentidad','1010',to_date('18/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('43','q','s','Cedula','2315',to_date('29/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('44','q','q','Cedula','1',to_date('29/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('53','q','q','Cedula','2',to_date('29/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('55','q','q','Cedula','1234222',to_date('29/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('1','Joan','Torres','Cedula','1233210',to_date('30/04/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('3','Joan','Torres','TarjetaIdentidad','912',to_date('01/05/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('21','as','as','Cedula','9852',to_date('08/05/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('22','Joan','Torres','Cedula','1024528884',to_date('03/05/92','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('23','Miguel','Mojica','Cedula','74080730',to_date('01/12/82','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('24','qqq','qqq','Cedula','123',to_date('01/01/01','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('25','qa','qa','Cedula','1793145268',to_date('02/05/18','DD/MM/RR'));
Insert into OW_JST_US.US_PSNA (PSNA_PSNA,PSNA_NOBR,PSNA_APDO,PSNA_TPDOC,PSNA_DOTO,PSNA_FCNA) values ('27','www','www','Cedula','456',to_date('01/01/01','DD/MM/RR'));
REM INSERTING into OW_JST_US.US_ROLS
SET DEFINE OFF;
Insert into OW_JST_US.US_ROLS (ROLS_ROLS,ROLS_NORS,ROLS_ESDO) values ('1','ADMINISTRADOR','1');
Insert into OW_JST_US.US_ROLS (ROLS_ROLS,ROLS_NORS,ROLS_ESDO) values ('2','DIRECTIVO','1');
Insert into OW_JST_US.US_ROLS (ROLS_ROLS,ROLS_NORS,ROLS_ESDO) values ('3','JUGADOR','1');
REM INSERTING into OW_JST_US.US_SRVI
SET DEFINE OFF;
REM INSERTING into OW_JST_US.US_SVRS
SET DEFINE OFF;
REM INSERTING into OW_JST_US.US_USRI
SET DEFINE OFF;
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('38','Qq1kk','C3C2BD601F0EC6A02ED4A4E55CC15B0B','0','38');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('41','Paris1','202CB962AC59075B964B07152D234B70','0','41');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('40','q1s2','C20AD4D76FE97759AA27A0C99BFF6710','0','40');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('42','qcs','C4CA4238A0B923820DCC509A6F75849B','0','42');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('43','qvag1','C4CA4238A0B923820DCC509A6F75849B','0','43');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('44','q1','C4CA4238A0B923820DCC509A6F75849B','0','44');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('53','q1w2','C4CA4238A0B923820DCC509A6F75849B','0','53');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('55','a','0CC175B9C0F1B6A831C399E269772661','0','55');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('1','joanst','C4CA4238A0B923820DCC509A6F75849B','0','1');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('3','a1','C4CA4238A0B923820DCC509A6F75849B','0','3');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('21','z1','FBADE9E36A3F36D3D676C1B808451DD7','0','21');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('22','joan123','92B37309315C5508FA979AF50AF52BA6','0','22');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('23','mamojica','179A4BAB5F12CEA23C872A0F024D09A5','0','23');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('24','qqq','B2CA678B4C936F905FB82F2733F5297F','0','24');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('25','x1','6DBF9AC2DA09EE1D3DEBF5A51873EC6D','0','25');
Insert into OW_JST_US.US_USRI (USRI_USRI,USRI_NUSR,USRI_CTUS,USRI_ESDO,USRI_PSNA) values ('27','www','4EAE35F1B35977A00EBD8086C259D4C9','0','27');
REM INSERTING into OW_JST_US.US_USRS
SET DEFINE OFF;
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','38');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','41');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','40');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','42');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','43');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','44');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','53');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','55');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','1');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','3');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','21');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('1','22');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','23');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','24');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('2','25');
Insert into OW_JST_US.US_USRS (USRS_ROLS,USRS_USRI) values ('3','27');
--------------------------------------------------------
--  DDL for Index PK_EQ_CVCT
--------------------------------------------------------
